### ISSUE TITLE
Hardcoded link, broken on staging site

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/csl-fall-2017#2]
https://github.com/redacademy/csl-fall-2017/blob/f5be5230eea6df9e9c3f09d3f2352360fb620f1f/themes/csl/front-page.php#L87

Try using get_post_type_archive_link instead... 

https://codex.wordpress.org/Function_Reference/get_post_type_archive_link

**Comment by rcass** [comment]
This doesn't look resolved, I am still the same code as pointed out above

https://github.com/redacademy/csl-fall-2017/blob/f5be5230eea6df9e9c3f09d3f2352360fb620f1f/themes/csl/front-page.php#L87

**Comment by ktrannn** [comment]
its updated on the develop branch!
